import express from 'express'
import crypto from 'crypto'
import bcrypt from 'bcrypt'
import jwt from 'jsonwebtoken'
import { Resend } from 'resend'
import pool from '../config/db.js'
import customerAuth from '../middleware/customerAuth.js'

const router = express.Router()

// ===============================
// RESEND EMAIL
// ===============================

const resend = new Resend(
  process.env.RESEND_API_KEY
)

// ===============================
// OTP SETTINGS
// ===============================

const OTP_EXPIRY_MINUTES = 5
const MAX_OTP_ATTEMPTS = 5
const OTP_RESEND_COOLDOWN_SECONDS = 60

// ===============================
// 2FACTOR SETTINGS
// ===============================

const TWOFACTOR_API_KEY =
  process.env.TWOFACTOR_API_KEY

const TWOFACTOR_TEMPLATE =
  'JAYAS_KITCHEN_OTP'

// ===============================
// OTP COOLDOWN STORAGE
// ===============================

const otpCooldowns = new Map()

// Clean old cooldown entries
setInterval(() => {
  const expiry =
    OTP_RESEND_COOLDOWN_SECONDS * 1000

  const now = Date.now()

  for (
    const [key, timestamp]
    of otpCooldowns.entries()
  ) {
    if (now - timestamp >= expiry) {
      otpCooldowns.delete(key)
    }
  }
}, 60 * 1000)

// ===============================
// CREATE CUSTOMER JWT
// ===============================

const createCustomerToken = (customer) => {
  return jwt.sign(
    {
      customerId: customer.id,
      email: customer.email,
      phone: customer.phone,
    },
    process.env.JWT_SECRET,
    {
      expiresIn: '7d',
    }
  )
}

// ===============================
// GENERATE OTP
// ===============================
//
// Used for EMAIL OTP and
// MOBILE OTP.
//
// Mobile OTP is generated by
// our backend and then sent to
// 2Factor using manual generation.
//

const generateOtp = () => {
  return crypto
    .randomInt(100000, 1000000)
    .toString()
}

// ===============================
// HASH OTP
// ===============================

const hashOtp = async (otp) => {
  return bcrypt.hash(otp, 10)
}

// ===============================
// VALIDATE MOBILE
// ===============================

const isValidPhone = (phone) => {
  return /^[0-9]{10}$/.test(phone)
}

// ===============================
// VALIDATE EMAIL
// ===============================

const isValidEmail = (email) => {
  return /^[^\s@]+@[^\s@]+\.[^\s@]+$/.test(
    email
  )
}

// ==================================================
// GET CURRENT LOGGED-IN CUSTOMER
// ==================================================

router.get(
  '/me',
  customerAuth,
  async (req, res) => {
    try {
      const customerId =
        req.customer?.customerId

      if (
        !customerId ||
        !Number.isInteger(
          Number(customerId)
        )
      ) {
        return res.status(401).json({
          success: false,
          message:
            'Invalid customer authentication.',
        })
      }

      const result =
        await pool.query(
          `
          SELECT
            id,
            name,
            phone,
            email,
            address,
            landmark,
            created_at,
            updated_at
          FROM customers
          WHERE id = $1
          LIMIT 1
          `,
          [Number(customerId)]
        )

      if (
        result.rows.length === 0
      ) {
        return res.status(404).json({
          success: false,
          message:
            'Customer account not found.',
        })
      }

      const customer =
        result.rows[0]

      return res.json({
        success: true,
        customer,
      })
    } catch (error) {
      console.error(
        'Fetch current customer failed:',
        error
      )

      return res.status(500).json({
        success: false,
        message:
          'Failed to fetch customer account.',
      })
    }
  }
)

// ==================================================
// UPDATE CURRENT LOGGED-IN CUSTOMER
// ==================================================

router.put(
  '/me',
  customerAuth,
  async (req, res) => {
    try {
      const customerId =
        req.customer?.customerId

      if (
        !customerId ||
        !Number.isInteger(
          Number(customerId)
        )
      ) {
        return res.status(401).json({
          success: false,
          message:
            'Invalid customer authentication.',
        })
      }

      const {
        name,
        phone,
        email,
      } = req.body

      const cleanName =
        typeof name === 'string'
          ? name.trim()
          : ''

      const cleanPhone =
        typeof phone === 'string'
          ? phone.trim()
          : ''

      const cleanEmail =
        typeof email === 'string'
          ? email.trim().toLowerCase()
          : ''

      if (!cleanName) {
        return res.status(400).json({
          success: false,
          message:
            'Full name is required.',
        })
      }

      if (cleanName.length > 100) {
        return res.status(400).json({
          success: false,
          message:
            'Full name must be 100 characters or less.',
        })
      }

      if (
        !cleanPhone ||
        !isValidPhone(cleanPhone)
      ) {
        return res.status(400).json({
          success: false,
          message:
            'Please enter a valid 10-digit mobile number.',
        })
      }

      if (
        cleanEmail &&
        !isValidEmail(cleanEmail)
      ) {
        return res.status(400).json({
          success: false,
          message:
            'Please enter a valid email address.',
        })
      }

      const phoneResult =
        await pool.query(
          `
          SELECT id
          FROM customers
          WHERE phone = $1
          AND id <> $2
          LIMIT 1
          `,
          [
            cleanPhone,
            Number(customerId),
          ]
        )

      if (
        phoneResult.rows.length > 0
      ) {
        return res.status(409).json({
          success: false,
          message:
            'This mobile number is already linked to another account.',
        })
      }

      if (cleanEmail) {
        const emailResult =
          await pool.query(
            `
            SELECT id
            FROM customers
            WHERE LOWER(email) = $1
            AND id <> $2
            LIMIT 1
            `,
            [
              cleanEmail,
              Number(customerId),
            ]
          )

        if (
          emailResult.rows.length > 0
        ) {
          return res.status(409).json({
            success: false,
            message:
              'This email address is already linked to another account.',
          })
        }
      }

      const result =
        await pool.query(
          `
          UPDATE customers
          SET
            name = $1,
            phone = $2,
            email = NULLIF($3, ''),
            updated_at = CURRENT_TIMESTAMP
          WHERE id = $4
          RETURNING
            id,
            name,
            phone,
            email,
            address,
            landmark,
            created_at,
            updated_at
          `,
          [
            cleanName,
            cleanPhone,
            cleanEmail,
            Number(customerId),
          ]
        )

      if (
        result.rows.length === 0
      ) {
        return res.status(404).json({
          success: false,
          message:
            'Customer account not found.',
        })
      }

      const customer =
        result.rows[0]

      const token =
        createCustomerToken(customer)

      return res.json({
        success: true,
        message:
          'Profile updated successfully.',
        token,
        customer,
      })
    } catch (error) {
      console.error(
        'Update customer profile failed:',
        error
      )

      return res.status(500).json({
        success: false,
        message:
          'Failed to update customer profile.',
      })
    }
  }
)

// ==================================================
// UPDATE SAVED DELIVERY ADDRESS
// ==================================================

router.put(
  '/me/address',
  customerAuth,
  async (req, res) => {
    try {
      const customerId =
        req.customer?.customerId

      if (
        !customerId ||
        !Number.isInteger(
          Number(customerId)
        )
      ) {
        return res.status(401).json({
          success: false,
          message:
            'Invalid customer authentication.',
        })
      }

      const {
        address,
        landmark,
      } = req.body

      const cleanAddress =
        typeof address === 'string'
          ? address.trim()
          : ''

      const cleanLandmark =
        typeof landmark === 'string'
          ? landmark.trim()
          : ''

      if (!cleanAddress) {
        return res.status(400).json({
          success: false,
          message:
            'Delivery address is required.',
        })
      }

      if (cleanAddress.length > 500) {
        return res.status(400).json({
          success: false,
          message:
            'Delivery address must be 500 characters or less.',
        })
      }

      if (cleanLandmark.length > 255) {
        return res.status(400).json({
          success: false,
          message:
            'Landmark must be 255 characters or less.',
        })
      }

      const result =
        await pool.query(
          `
          UPDATE customers
          SET
            address = $1,
            landmark = NULLIF($2, ''),
            updated_at = CURRENT_TIMESTAMP
          WHERE id = $3
          RETURNING
            id,
            name,
            phone,
            email,
            address,
            landmark,
            created_at,
            updated_at
          `,
          [
            cleanAddress,
            cleanLandmark,
            Number(customerId),
          ]
        )

      if (
        result.rows.length === 0
      ) {
        return res.status(404).json({
          success: false,
          message:
            'Customer account not found.',
        })
      }

      const customer =
        result.rows[0]

      const token =
        createCustomerToken(customer)

      return res.json({
        success: true,
        message:
          'Delivery address saved successfully.',
        token,
        customer,
      })
    } catch (error) {
      console.error(
        'Update customer address failed:',
        error
      )

      return res.status(500).json({
        success: false,
        message:
          'Failed to save delivery address.',
      })
    }
  }
)

// ===============================
// SEND OTP
// ===============================

router.post('/send', async (req, res) => {
  try {
    const {
      method,
      phone,
      email,
      name,
    } = req.body

    const now = Date.now()

    // ===============================
    // VALIDATE METHOD
    // ===============================

    if (
      method !== 'mobile' &&
      method !== 'email'
    ) {
      return res.status(400).json({
        success: false,
        message:
          'Invalid OTP method.',
      })
    }

    // ===============================
    // MOBILE OTP
    // ===============================

    if (method === 'mobile') {
      const cleanPhone =
        typeof phone === 'string'
          ? phone.trim()
          : ''

      if (
        !cleanPhone ||
        !isValidPhone(cleanPhone)
      ) {
        return res.status(400).json({
          success: false,
          message:
            'Please enter a valid 10-digit mobile number.',
        })
      }

      // --------------------------------
      // CHECK 2FACTOR API KEY
      // --------------------------------

      if (!TWOFACTOR_API_KEY) {
        console.error(
          'TWOFACTOR_API_KEY is missing.'
        )

        return res.status(500).json({
          success: false,
          message:
            'Mobile OTP service is not configured.',
        })
      }

      // --------------------------------
      // MOBILE OTP COOLDOWN
      // --------------------------------

      const cooldownKey =
        `mobile:${cleanPhone}`

      const lastSentAt =
        otpCooldowns.get(cooldownKey)

      if (
        lastSentAt &&
        now - lastSentAt <
          OTP_RESEND_COOLDOWN_SECONDS * 1000
      ) {
        const remainingSeconds =
          Math.ceil(
            (
              OTP_RESEND_COOLDOWN_SECONDS * 1000 -
              (now - lastSentAt)
            ) / 1000
          )

        return res.status(429).json({
          success: false,
          message:
            `Please wait ${remainingSeconds} seconds before requesting another OTP.`,
          retryAfter:
            remainingSeconds,
        })
      }

      // --------------------------------
      // FIND CUSTOMER
      // --------------------------------

      const customerResult =
        await pool.query(
          `
          SELECT
            id,
            name,
            phone,
            email
          FROM customers
          WHERE phone = $1
          LIMIT 1
          `,
          [cleanPhone]
        )

      const customer =
        customerResult.rows[0] || null

      // --------------------------------
      // LOGIN CUSTOMER MUST EXIST
      // --------------------------------

      if (!name && !customer) {
        return res.status(404).json({
          success: false,
          message:
            'No account found with this mobile number. Please create an account first.',
        })
      }

      // --------------------------------
      // GENERATE OTP
      // --------------------------------

      const otp = generateOtp()

      console.log(
        `Generated mobile OTP for ${cleanPhone}`
      )

      // --------------------------------
      // SEND OTP THROUGH 2FACTOR
      // MANUAL GENERATION
      // --------------------------------

      const internationalPhone =
        `+91${cleanPhone}`

      const twoFactorUrl =
        `https://2factor.in/API/V1/${encodeURIComponent(
          TWOFACTOR_API_KEY
        )}/SMS/${encodeURIComponent(
          internationalPhone
        )}/${encodeURIComponent(
          otp
        )}/${encodeURIComponent(
          TWOFACTOR_TEMPLATE
        )}`

      console.log(
        `Sending mobile OTP through 2Factor to ${internationalPhone}`
      )

      const twoFactorResponse =
        await fetch(twoFactorUrl, {
          method: 'GET',
          headers: {
            Accept:
              'application/json',
          },
        })

      const twoFactorData =
        await twoFactorResponse.json()

      console.log(
        '2Factor send OTP response:',
        twoFactorData
      )

      // --------------------------------
      // CHECK 2FACTOR RESPONSE
      // --------------------------------

      if (
        !twoFactorResponse.ok ||
        twoFactorData?.Status !==
          'Success'
      ) {
        console.error(
          '2Factor OTP sending failed:',
          twoFactorData
        )

        return res.status(500).json({
          success: false,
          message:
            'Unable to send OTP to your mobile number. Please try again.',
        })
      }

      // --------------------------------
      // START MOBILE COOLDOWN
      // --------------------------------

      otpCooldowns.set(
        cooldownKey,
        Date.now()
      )

      return res.json({
        success: true,
        message:
          'OTP sent successfully to your mobile number.',
        expiresIn:
          OTP_EXPIRY_MINUTES * 60,
      })
    }

    // ===============================
    // EMAIL OTP
    // ===============================

    if (method === 'email') {
      const cleanEmail =
        typeof email === 'string'
          ? email.trim().toLowerCase()
          : ''

      if (
        !cleanEmail ||
        !isValidEmail(cleanEmail)
      ) {
        return res.status(400).json({
          success: false,
          message:
            'Please enter a valid email address.',
        })
      }

      const cooldownKey =
        `email:${cleanEmail}`

      const lastSentAt =
        otpCooldowns.get(cooldownKey)

      if (
        lastSentAt &&
        now - lastSentAt <
          OTP_RESEND_COOLDOWN_SECONDS * 1000
      ) {
        const remainingSeconds =
          Math.ceil(
            (
              OTP_RESEND_COOLDOWN_SECONDS * 1000 -
              (now - lastSentAt)
            ) / 1000
          )

        return res.status(429).json({
          success: false,
          message:
            `Please wait ${remainingSeconds} seconds before requesting another OTP.`,
          retryAfter:
            remainingSeconds,
        })
      }

      const customerResult =
        await pool.query(
          `
          SELECT
            id,
            name,
            phone,
            email
          FROM customers
          WHERE LOWER(email) = $1
          LIMIT 1
          `,
          [cleanEmail]
        )

      const customer =
        customerResult.rows[0] || null

      if (!name && !customer) {
        return res.status(404).json({
          success: false,
          message:
            'No account found with this email address. Please create an account first.',
        })
      }

      const otp = generateOtp()

      const otpHash =
        await hashOtp(otp)

      const expiresAt =
        new Date(
          Date.now() +
            OTP_EXPIRY_MINUTES *
              60 *
              1000
        )

      await pool.query(
        `
        DELETE FROM customer_otps
        WHERE LOWER(email) = $1
        AND verified = FALSE
        `,
        [cleanEmail]
      )

      await pool.query(
        `
        INSERT INTO customer_otps (
          customer_id,
          email,
          otp_hash,
          expires_at
        )
        VALUES ($1, $2, $3, $4)
        `,
        [
          customer?.id || null,
          cleanEmail,
          otpHash,
          expiresAt,
        ]
      )

      // ===============================
      // SEND EMAIL WITH RESEND
      // ===============================

      const {
        data,
        error,
      } = await resend.emails.send({
        from:
          "Jaya's Kitchen <onboarding@resend.dev>",

        to: [cleanEmail],

        subject:
          "Your Jaya's Kitchen Login OTP",

        html: `
          <div style="
            font-family: Arial, sans-serif;
            background-color: #f8faf6;
            padding: 30px 15px;
          ">
            <div style="
              max-width: 500px;
              margin: 0 auto;
              background: #ffffff;
              border-radius: 12px;
              padding: 30px;
              border: 1px solid #e5e7eb;
            ">

              <h2 style="
                margin: 0 0 10px;
                color: #166534;
              ">
                Jaya's Kitchen
              </h2>

              <p style="
                color: #374151;
                font-size: 15px;
              ">
                Your verification code is:
              </p>

              <div style="
                margin: 25px 0;
                text-align: center;
              ">
                <span style="
                  display: inline-block;
                  padding: 14px 24px;
                  background: #f0fdf4;
                  border: 1px solid #bbf7d0;
                  border-radius: 10px;
                  color: #166534;
                  font-size: 32px;
                  font-weight: bold;
                  letter-spacing: 8px;
                ">
                  ${otp}
                </span>
              </div>

              <p style="
                color: #4b5563;
                font-size: 14px;
              ">
                This OTP is valid for
                <strong>5 minutes</strong>.
              </p>

              <p style="
                color: #6b7280;
                font-size: 13px;
              ">
                If you did not request this code,
                you can safely ignore this email.
              </p>

              <hr style="
                border: none;
                border-top: 1px solid #e5e7eb;
                margin: 25px 0;
              ">

              <p style="
                color: #9ca3af;
                font-size: 12px;
                margin: 0;
              ">
                Jaya's Kitchen — Home Tiffin & Catering
              </p>

            </div>
          </div>
        `,
      })

      if (error) {
        console.error(
          'Resend email error:',
          error
        )

        await pool.query(
          `
          DELETE FROM customer_otps
          WHERE LOWER(email) = $1
          AND verified = FALSE
          `,
          [cleanEmail]
        )

        return res.status(500).json({
          success: false,
          message:
            'Unable to send OTP email. Please try again.',
        })
      }

      otpCooldowns.set(
        cooldownKey,
        Date.now()
      )

      console.log(
        `OTP email sent successfully. Resend ID: ${
          data?.id || 'unknown'
        }`
      )

      return res.json({
        success: true,
        message:
          'OTP sent successfully to your email.',
        expiresIn:
          OTP_EXPIRY_MINUTES * 60,
      })
    }
  } catch (error) {
    console.error(
      'Send OTP error:',
      error
    )

    return res.status(500).json({
      success: false,
      message:
        'Unable to send OTP.',
    })
  }
})

// ===============================
// VERIFY OTP
// ===============================

router.post('/verify', async (req, res) => {
  try {
    const {
      method,
      phone,
      email,
      otp,
      name,
    } = req.body

    // ===============================
    // VALIDATE METHOD
    // ===============================

    if (
      method !== 'mobile' &&
      method !== 'email'
    ) {
      return res.status(400).json({
        success: false,
        message:
          'Invalid OTP method.',
      })
    }

    // ===============================
    // VALIDATE OTP
    // ===============================

    if (
      !otp ||
      !/^[0-9]{6}$/.test(otp)
    ) {
      return res.status(400).json({
        success: false,
        message:
          'Please enter a valid 6-digit OTP.',
      })
    }

    let customer = null
    let otpRecord = null

    // ===============================
    // MOBILE OTP
    // ===============================

    if (method === 'mobile') {
      const cleanPhone =
        typeof phone === 'string'
          ? phone.trim()
          : ''

      if (
        !cleanPhone ||
        !isValidPhone(cleanPhone)
      ) {
        return res.status(400).json({
          success: false,
          message:
            'Please enter a valid 10-digit mobile number.',
        })
      }

      // --------------------------------
      // CHECK 2FACTOR API KEY
      // --------------------------------

      if (!TWOFACTOR_API_KEY) {
        console.error(
          'TWOFACTOR_API_KEY is missing.'
        )

        return res.status(500).json({
          success: false,
          message:
            'Mobile OTP service is not configured.',
        })
      }

      // --------------------------------
      // VERIFY OTP THROUGH 2FACTOR
      // --------------------------------

      const internationalPhone =
        `+91${cleanPhone}`

      const twoFactorVerifyUrl =
        `https://2factor.in/API/V1/${encodeURIComponent(
          TWOFACTOR_API_KEY
        )}/SMS/VERIFY3/${encodeURIComponent(
          internationalPhone
        )}/${encodeURIComponent(
          otp
        )}`

      console.log(
        `Verifying mobile OTP through 2Factor for ${internationalPhone}`
      )

      const twoFactorResponse =
        await fetch(
          twoFactorVerifyUrl,
          {
            method: 'GET',
            headers: {
              Accept:
                'application/json',
            },
          }
        )

      const twoFactorData =
        await twoFactorResponse.json()

      console.log(
        '2Factor verify OTP response:',
        twoFactorData
      )

      // --------------------------------
      // CHECK 2FACTOR VERIFICATION
      // --------------------------------

      if (
        !twoFactorResponse.ok ||
        twoFactorData?.Status !==
          'Success'
      ) {
        return res.status(401).json({
          success: false,
          message:
            'Incorrect or expired OTP. Please try again.',
        })
      }

      // --------------------------------
      // FIND CUSTOMER
      // --------------------------------

      const customerResult =
        await pool.query(
          `
          SELECT
            id,
            name,
            phone,
            email,
            address,
            landmark,
            created_at,
            updated_at
          FROM customers
          WHERE phone = $1
          LIMIT 1
          `,
          [cleanPhone]
        )

      customer =
        customerResult.rows[0] || null

      // ===============================
      // CREATE CUSTOMER
      // ===============================

      if (!customer) {
        if (!name) {
          return res.status(400).json({
            success: false,
            message:
              'Full name is required to create an account.',
          })
        }

        const cleanName =
          typeof name === 'string'
            ? name.trim()
            : ''

        if (!cleanName) {
          return res.status(400).json({
            success: false,
            message:
              'Please enter your full name.',
          })
        }

        if (cleanName.length > 100) {
          return res.status(400).json({
            success: false,
            message:
              'Full name must be 100 characters or less.',
          })
        }

        const result =
          await pool.query(
            `
            INSERT INTO customers (
              name,
              phone
            )
            VALUES ($1, $2)
            RETURNING
              id,
              name,
              phone,
              email,
              address,
              landmark,
              created_at,
              updated_at
            `,
            [
              cleanName,
              cleanPhone,
            ]
          )

        customer =
          result.rows[0]
      }

      // --------------------------------
      // CLEAR MOBILE COOLDOWN
      // --------------------------------

      otpCooldowns.delete(
        `mobile:${cleanPhone}`
      )

      // --------------------------------
      // CREATE JWT
      // --------------------------------

      const token =
        createCustomerToken(customer)

      return res.json({
        success: true,
        message:
          'OTP verified successfully.',
        token,
        customer,
      })
    }

    // ===============================
    // EMAIL OTP
    // ===============================

    if (method === 'email') {
      const cleanEmail =
        typeof email === 'string'
          ? email.trim().toLowerCase()
          : ''

      if (
        !cleanEmail ||
        !isValidEmail(cleanEmail)
      ) {
        return res.status(400).json({
          success: false,
          message:
            'Please enter a valid email address.',
        })
      }

      const otpResult =
        await pool.query(
          `
          SELECT *
          FROM customer_otps
          WHERE LOWER(email) = $1
          AND verified = FALSE
          ORDER BY created_at DESC
          LIMIT 1
          `,
          [cleanEmail]
        )

      otpRecord =
        otpResult.rows[0] || null

      const customerResult =
        await pool.query(
          `
          SELECT
            id,
            name,
            phone,
            email,
            address,
            landmark,
            created_at,
            updated_at
          FROM customers
          WHERE LOWER(email) = $1
          LIMIT 1
          `,
          [cleanEmail]
        )

      customer =
        customerResult.rows[0] || null

      if (!otpRecord) {
        return res.status(400).json({
          success: false,
          message:
            'OTP not found or expired. Please request a new OTP.',
        })
      }

      if (
        new Date(otpRecord.expires_at) <
        new Date()
      ) {
        await pool.query(
          `
          DELETE FROM customer_otps
          WHERE id = $1
          `,
          [otpRecord.id]
        )

        return res.status(400).json({
          success: false,
          message:
            'OTP has expired. Please request a new OTP.',
        })
      }

      if (
        otpRecord.attempts >=
        MAX_OTP_ATTEMPTS
      ) {
        await pool.query(
          `
          DELETE FROM customer_otps
          WHERE id = $1
          `,
          [otpRecord.id]
        )

        return res.status(429).json({
          success: false,
          message:
            'Too many incorrect attempts. Please request a new OTP.',
        })
      }

      const otpMatches =
        await bcrypt.compare(
          otp,
          otpRecord.otp_hash
        )

      if (!otpMatches) {
        await pool.query(
          `
          UPDATE customer_otps
          SET attempts = attempts + 1
          WHERE id = $1
          `,
          [otpRecord.id]
        )

        return res.status(401).json({
          success: false,
          message:
            'Incorrect OTP. Please try again.',
        })
      }

      await pool.query(
        `
        UPDATE customer_otps
        SET verified = TRUE
        WHERE id = $1
        `,
        [otpRecord.id]
      )

      // --------------------------------
      // CREATE EMAIL CUSTOMER
      // --------------------------------

      if (!customer) {
        if (!name) {
          return res.status(400).json({
            success: false,
            message:
              'Full name is required to create an account.',
          })
        }

        const cleanName =
          typeof name === 'string'
            ? name.trim()
            : ''

        if (!cleanName) {
          return res.status(400).json({
            success: false,
            message:
              'Please enter your full name.',
          })
        }

        if (cleanName.length > 100) {
          return res.status(400).json({
            success: false,
            message:
              'Full name must be 100 characters or less.',
          })
        }

        const result =
          await pool.query(
            `
            INSERT INTO customers (
              name,
              phone,
              email
            )
            VALUES ($1, $2, $3)
            RETURNING
              id,
              name,
              phone,
              email,
              address,
              landmark,
              created_at,
              updated_at
            `,
            [
              cleanName,
              '',
              cleanEmail,
            ]
          )

        customer =
          result.rows[0]
      }

      const token =
        createCustomerToken(customer)

      await pool.query(
        `
        DELETE FROM customer_otps
        WHERE id = $1
        `,
        [otpRecord.id]
      )

      otpCooldowns.delete(
        `email:${cleanEmail}`
      )

      return res.json({
        success: true,
        message:
          'OTP verified successfully.',
        token,
        customer,
      })
    }
  } catch (error) {
    console.error(
      'Verify OTP error:',
      error
    )

    return res.status(500).json({
      success: false,
      message:
        'Unable to verify OTP.',
    })
  }
})

export default router